# Generated by Django 5.0 on 2024-01-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbankaccount',
            name='is_bancrupt',
            field=models.BooleanField(default=False),
        ),
    ]
